language: C
sudo: required
dist: trusty

addons:
  apt:
    packages:
    - libtool
    - libglib2.0-dev
    - libmagic-dev
    - libxml2-dev
    - libjson-c-dev
    - libmicrohttpd-dev
    - libcurl4-openssl-dev


before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

compiler:
  - gcc

before_script:
  - git clone git://github.com/armadito/armadito-av -b DEV
  - cd armadito-av/core
  - ./autogen.sh
  - ./configure --prefix=~/armadito-core PKG_CONFIG_PATH=~/armadito-core/lib/pkgconfig
  - make
  - make install
  - cd ../../

script:
  ./configure && make clean && make && make check
