language: C
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - libtool
    - libglib2.0-dev
    - libmagic-dev
    - libxml2-dev
    - libmicrohttpd-dev
    - libcurl4-openssl-dev
    - libjansson-dev
    - libjansson4
    - autoconf-archive
  coverity_scan:
    project:
      name: armadito/armadito-mod-h1
      description: Build submitted via Travis CI
    notification_email: vhamon@teclib.com
    build_command_prepend: "./configure PKG_CONFIG_PATH=/home/travis/build/armadito-core/lib/pkgconfig;
      make clean"
    build_command: make -j 4
    branch_pattern: coverity_scan
  sonarqube: true
deploy:
  skip_cleanup: true
  provider: launchpad
  slug: "~armadito/armadito-mod-h1/+git/main"
  oauth_token:
    secure: iBdMp37oigwoubTHpSg0I9V1vgT7DrCSGsRDsGhwtTjfbbEnFrmxZBYbt/999Z6StN3lYC9mQovmoHksaOUcv34E4HPYGUJ3Tx65j6M/GfJqOWNCtTs6hfX9btZlBXcy8CwUyJf30sSTHRmb0x4xuf42TAuR8vhj+1R788Be99kZoRqZiMw+yONwa2ZHAe8lDguxjy1CszGKsienn+jIScnXPgTIUAqYzZsSeQu/OOiZO3oFZsT/DEpXWRKj4JhZ8FccfaAnu7O5oj4zoVrMhOMEa2cD1W3jZ3u2jAvNPU1cAH9jxJDUva4EoRwcflkDspty7jQMOpZNwyB1il+O0Kyf/r3ur6AY/mKU2nZn6hTQUZsCeiTR0+wNOA23a6TdVDZazTshq7SKzMEGHBPMnKHvLtF+kskV/j8arSNAbTA+NhmqWp64qajDkjUsAKXFcB3Ged1DEJXnOwTQ4VMnY92mzvMqjbWUXjONq/kXDw9wu3JzdvI/YgUEZR8LXQn8qtm+6VPj3QT2wrBdNE/au7bMe2uMZcicMAEpR6ztk8WXCyKvfGS26mQNeYcnaK3zjjqrozG/0ZD4vhO+/ltVLg5luKGFDgivpBrtA3fbChCOOO2qozAHEUvkXPKL0pU45HXhjb4bTqSJbfI8CLYK4woSh8Vtti8ai1BLEDK/eNo=
  oauth_token_secret:
    secure: t2x5/eRiRnsf1waomuLqG3AMPo8gymgkHIfkOrZhfNKdLLFRgFaR1kUqtZbHLcJg5tAVTShw03rWZrnEFg0ZTE7pr0javLQvKuhsUPOU017mT0D67j/+fhRpShcWqEo/gg+vxMssY7kV1S/QTma3JT4xgqBc+MWwwlZtS5PqlV4wmgI6uux8IStmKfDAe/brRxkepu87PJVfh21vGn3U0uHNIFGUB62ugTfa3t7RxZIP9Jqwg9NNy2hYDyR/jNCQXA6+ZwPB4lJ/4y7PIwQupcPqr8xkcEjBNcjxLB3Jr7c29TphKc0150sXPk5iU0CU2yhyl6jDn4OLNoG6T5PfFrhvP4FyPH39VTkEDB7Hp4od4ePzi2ux+0m08Kyx0hLYwQL0IhDSJ51NluHED6uYolJnWrYEoestNvH2jgqr+lwps7Rz17smfZT1+PPOyLZ9lfcQ98k8gKKEsOnQ0/JKjgvNflav/tC+u8J+zhuSmXcDA4jzSrXcjiWJjxZXv4rjtWyYSLfz4UxZOCPYzzEvpPGG7aWuQmxaDorJGo2JWJ5tWGP/c+9q5I1s4VzY82+2Mf4GbtqlCTKego0s7yyWnK/WQjkB/XeXXjZAffZt4YLLctVunVYGAYG6iy16WvIrLKeHRCL3enRIFaD2Gdz5R0LZ/gGtQRujAGjcMpE0qCs=
  on:
    tags: true
env:
  global:
  - secure: VBRuucKW724c/FVLkSzWaePaQtHDUinBN6qZ1dQzLteQUvIGi5x7UIBBPHO+78L+rNPFYXi4fC0v/6F7JjU+STuHm5sAsXyo9vu3g1d6Hr6D9LYe2j+oVU4MGO9LPU74rbnINHhQ8/TEZbFfWWaRE7RSo66cZA4WygFyeUAlCPEB/d6Aw8P6zg66OSJ8Ti4n4EpUXpU0auBZbxjgRJNA6qkg1Nf1x2CM2IdhJbrDYB2xHKcw3z4++7872EJLcqWP++5V90fgYQEq2iaR5uOlZYsD7T3ZuRfC524eqK2CFMddceza7UjBlOkAq9Tex97e5LDTWgzd0g29cVfbOOo5kMbrZYlvXrX7W4/uQ4rnai/t1u+/VIlzYJYJZwloR7eFgStIZeKSjBkMwYUteYr/hvkSrz3bmkSsiWVJ4UYxKv+PszIm3k39qfWmYJbjCBpiICVLEsQ5tKXac8cUX/fPYGmSLPYbWxWlJtoQM5gynn1bvRa2giG8zq9x2R0+U33FTJm7bh1yyL9vLv6p25sDmxfH2u2JbI2mshN0MnOL26soaueSaJrH8MpD/58q64vaV2x9d7pZDuBqLIV6QkTDDfYv1g33QZcoTVMBXQyL5ku+XC7smOTziH20y96jEGTD8ztJk81ACSNgFCtRC0fC8RUrDOgG5YBoehvU4cdEVw=
  - secure: d6JZz/DJ8gOR7ikFjDSxFTaGzyMSBiYkHQsiVmssrkl3dNspAlnlAyNRjfN9GF6t4jjOUNbI5D6LicMURV8tQnT9DBJAwcnzD+FmgsraMlrWN70TaQEkQeG2vipC9M68hNiafBNAqT3FusOdHV+s4rV/MuXZP6SMFbxfYsJ446slB76CvaB7Qc+hutIquesfOfndDwwhCaYwYwVKoi+aobW1trGIJX5oAbVVScuziPP0mXPcfYAQ/vXNcot3KqgkvJL+5jh3pIkOnxyXC/FBylCp7y9+Ms+WwYbIfyTV2toojFFWnLSliTbQlF7uXDrfi7iF02pulcaCVyU/hkujHGCYwwXlOgz8Nh4g3MwHOwUSKeOJQp5OnwKZ4E4ljsuRJ0tQGUbXDE84pBC6A+ojPxyW1IzWgbBedsJSEF43xd3q6EFxNStKAsx9RCOaGWe3dxtSE1JK6SObjna6CXSj6Zv6sJBtnqAJaUwq04PtZNPI3IOfHZshF8z/LsrGNPoqItSZXekXhsf9UQFi+DgV8vkbl38rNJuaLeJxZ54h+jTKuaBWSnb5yywOhAqcflV/88xEjDeJoE3Kt0XKU1qSAAdZrVcdejGkjDc6WIEFABYNDkQk3DeufEZiunjn1qkVwxM4mD/Ovg1qJLBPSOce87tZPyUmCyVN0WV2ln/vjCc=
before_install:
- echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END
  CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
- wget https://sonarqube.com/static/cpp/build-wrapper-linux-x86.zip
- unzip build-wrapper-linux-x86.zip
- export PATH=$PWD/build-wrapper-linux-x86:$PATH
compiler:
- gcc
before_script:
- git clone git://github.com/armadito/armadito-av -b DEV
- cd armadito-av/
- "./autogen.sh"
- mkdir -p /home/travis/build/armadito-core
- "./configure --prefix=/home/travis/build/armadito-core"
- make
- make install
- cd /home/travis/build/armadito/armadito-mod-h1
- "./autogen.sh"
script:
- "./configure PKG_CONFIG_PATH=/home/travis/build/armadito-core/lib/pkgconfig"
- build-wrapper-linux-x86-64 --out-dir build-wrapper-out make clean all
- sonar-scanner -X -Dsonar.host.url=https://sonarqube.com -Dsonar.login=$SONAR_TOKEN
